version: "3.7"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=pojan
    #   - MONGO_INITDB_ROOT_PASSWORD=pojan
    env_file:
      - ./env/mongo.env
    # networks:
    #   - goals-net
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    # some-arg:1
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
